### ISSUE TITLE
Hoppers taking items out of private chests

### ISSUE THREAD

**Issue by TheMightyCat** [rutgerkok/BlockLocker#17] opened 2019-01-19 10:21 UTC
The stuff in a private chest can be easily stolen by using a hopper to transfer the items to another chest. Please fix it.

**Comment by rutgerkok** [comment] 2019-01-19 19:19
Cannot reproduce. I just attached a hopper to a chest and the items stayed in the chest.

Did you add `[Everyone]` or `[Redstone]` to the sign?

**Comment by rutgerkok** [comment] 2019-09-14 05:43
Closing this, in hindsight I assume that this is just another case of https://www.spigotmc.org/threads/blocklocker.44937/page-13#post-3545164 . I've added this bug to the FAQ on the main page of the plugin.

**Closed by rutgerkok** 2019-09-14 05:43 UTC
Labels: cannot reproduce
